[package]
name = "monoidal-categories"
version = "0.1"
path = "src"

[dependencies]
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "11c2268aa8f5035eb2440a3c4d85b32c0b6ccf55"}
