[package]
name = "monoidal-categories"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "69a0433270e634acfe48a9f816558669213fc747"}
