[package]
name = "monoidal-categories"
version = "0.1"

[dependencies]
lean-category-theory = { git = "https://github.com/semorrison/lean-category-theory", rev = "1ef1b1b40e078bce62e8b9dcce2e77bc07dc800c" }
