[package]
name = "monoidal-categories"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "43fce877b27b7e05a908d3887bce448e50a5fe1e"}
